### ISSUE TITLE
occasionally the member count token remains instead of being replaced by number

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/mbc-digest-email#34]
In the "footer" - Make an impact with 3.5 million members. Any cause, anytime, anywhere. *mic drop*

![image](https://cloud.githubusercontent.com/assets/6330971/6759671/2c25f14e-cf18-11e4-823b-0b8aae7f5a3f.png)

vs. 

![image](https://cloud.githubusercontent.com/assets/6330971/6759675/37426bac-cf18-11e4-8913-c85069ecd339.png)

**Comment by DeeZone** [comment]
Hmm, looks like the Drupal API is not responding when the digest is being built. Is this random (some digests have it, some don't all within the day) or is there a pattern you can see (only certain email address, works today, not yesterday)?

**Comment by mikefantini** [comment]
@DeeZone it only happened on the first email I received to mfantini@dosomething.org which occured on Mon, Mar 16, 2015 at 9:47 AM and not any of the subsequent 20+ I received.

**Comment by DeeZone** [comment]
@mikefantini Noted, I've put some error checking, fallback code in place to deal with this so the merge tag is not displayed in the Mandrill message.

Please re-open this issue if you see it again.

**Comment by mikefantini** [comment]
sounds good @DeeZone you may want to add a new tester to the mix and have her/him look out for this specifically in the first email s/he receives

**Comment by DeeZone** [comment]
@apatheticslacker Can you please put this issue "member count token undefined" on your list of items to test with a new email address?
