### ISSUE TITLE
Unsubscribe Functionality Not Working

### ISSUE THREAD

**Issue by apatheticslacker** [DoSomething/mbc-digest-email#35]
On the email digests, selecting the unsubscribe link takes you to an unavailable site: 

![image](https://cloud.githubusercontent.com/assets/7773483/6805622/571ccd64-d21a-11e4-9f25-c1774b10d39a.png)

**Comment by apatheticslacker** [comment]
Forgot to include the relevant emails and links:

- apatheticslacker@gmail.com 

 http://subscriptions.dosomething.org/?targetEmail=apatheticslacker%40gmail.com&key=644dc37c2e694b0b3051c13836f187de
- jvicente@nyit.edu 

 http://subscriptions.dosomething.org/?targetEmail=jvicente%40nyit.edu&key=a6e99413d395d57bc9756783e04400c2

**Comment by DeeZone** [comment]
@apatheticslacker Try them again as I was able to get them to work. I'll attach screenshots later.

**Comment by apatheticslacker** [comment]
@DeeZone It somewhat works now, but for some reason it's saying the most recent unsubscribe link from the last email digest that was sent out today is giving me denied access: 
![image](https://cloud.githubusercontent.com/assets/7773483/6807082/c529004a-d222-11e4-9400-a87b8e2b1aa8.png)
It's still not working on the jvicente@nyit.edu account however.

**Comment by DeeZone** [comment]
- Confirmed for http://subscriptions.dosomething.org/?targetEmail=apatheticslacker%40gmail.com&key=644dc37c2e694b0b3051c13836f187de

- How about: http://subscriptions.dosomething.org/?targetEmail=jvicente%40nyit.edu&key=a6e99413d395d57bc9756783e04400c2 ??

**Comment by apatheticslacker** [comment]
It still gives me this same error page: 
![image](https://cloud.githubusercontent.com/assets/7773483/6807286/f4d14e64-d223-11e4-9db8-57047fb0f70f.png)
I'm not entirely sure if it's a connection issue on my end or something.
