### ISSUE TITLE
Mixed Font Colors on Digests

### ISSUE THREAD

**Issue by apatheticslacker** [DoSomething/mbc-digest-email#36]
On some of the email digests that I've received so far, text between some campaigns is mixed with purple and black. Some digests all together have had just purple text rather than black. So far I've seen this on both the apatheticslacker@gmail.com email along with the jvicente@nyit.edu account.
![purpletext](https://cloud.githubusercontent.com/assets/7773483/6851188/d2a31390-d3b3-11e4-8911-785428f4358f.jpg)

**Comment by DeeZone** [comment]
@weerd Can I get you to look at this?
