### ISSUE TITLE
Unsubscribe Link Missing [Yahoo] 

### ISSUE THREAD

**Issue by apatheticslacker** [DoSomething/mbc-digest-email#40]
On the current round of email digests for the qualityassuranceqa@yahoo.com, the unsubscribe section of the email just has the content for unsubscribing, but the link for unsubscribe isn't opening. 
![image](https://cloud.githubusercontent.com/assets/7773483/7025548/65bb8790-dd12-11e4-975c-ebe6002945bd.png)

**Comment by DeeZone** [comment]
Specific to Yahoo,
