### ISSUE TITLE
Unsubscribe link leads to error message

### ISSUE THREAD

**Issue by marahml** [DoSomething/mbc-digest-email#44]
email address: mlidey@dosomething.org

link: http://subscriptions.dosomething.org/?targetEmail=mlidey%40dosomething.org&key=db0a329d94b8c726573710bd535a97d8

![screen shot 2015-04-09 at 11 49 55 am](https://cloud.githubusercontent.com/assets/6784628/7070724/baaef92e-deae-11e4-9f04-02ed325cb64a.png)

**Comment by DeeZone** [comment]
I think this issue has been resolved. Please delete / disregard all digest messages sent to you at this time: 13 APril 205, 8pm. Attempt to use the unsubscribe line on a new message.
