### ISSUE TITLE
Not being unsubscribed from Digest 

### ISSUE THREAD

**Issue by deadlybutter** [DoSomething/mbc-digest-email#48]
Receiving campaign digest emails on my joe@dosomething email

![screen shot 2015-04-14 at 2 32 02 pm](https://cloud.githubusercontent.com/assets/897368/7144532/35f271a2-e2b4-11e4-9469-838b59bc7807.png)

Even though I've been unsubscribed for multiple days 

![screen shot 2015-04-14 at 2 32 13 pm](https://cloud.githubusercontent.com/assets/897368/7144537/409328ea-e2b4-11e4-8cc6-a4969aca5afb.png)

**Comment by DeeZone** [comment]
@barryclark 
@deadlybutter This issue has been resolved, can you retest and report back to this issue please.
