### ISSUE TITLE
"Additional Info" Field Isn't Over-riding Tips

### ISSUE THREAD

**Issue by ArielSD** [DoSomething/mbc-digest-email#68]
When sending digest tests, content is populating from the "Do It" field, even when "Additional Info" is filled out. Additional info should over-ride the content in the "Do It" field. 

Last week's digest was perfectly functional, this issue is new this week. 

@DeeZone I don't have permissions to assign or tag in this repo.

**Comment by DeeZone** [comment]
Please provide a screenshot of the digest message as well as a description of what is expected. The names / nid of the campaigns where the bug appears.

**Comment by ArielSD** [comment]
@DeeZone Good to close this one then, eh?
