### ISSUE TITLE
Campaigns Signed Up for Long Ago Appearing in Email Digest

### ISSUE THREAD

**Issue by namimody** [DoSomething/mbc-digest-email#78]
#### Current Behavior

Seems like campaigns that people signed up for a long time ago and haven't reported back on are being mentioned in email digests. An old temp of mine who likely signed up for a campaign in 2014 got the digest for Birthday Mail (UID 2012144). Weirdly, the campaign isn't appearing on her user profile -- perhaps because a different run of the campaign is current now?

#### Desired Behavior

Not sure...Marah?

#### Relevant Screenshots + Links

![image](https://cloud.githubusercontent.com/assets/12396076/13237342/52c5f0a6-d999-11e5-94e0-0a88057bb60b.png)

**Comment by DeeZone** [comment]
Fixed by Issue #65
